### ISSUE TITLE
好像这个其实什么都没做？

### ISSUE THREAD

**Issue by nighca** [luqin/react-echarts#2]
所以是不做封装了，建议直接使用 echarts 模块对吗

**Comment by luqin** [comment]
是的，刚创建。因为目前通过直接使用良好

**Comment by nighca** [comment]
我这遇到的情况是：

1、 echarts 本身实现代码量很大，import 进来会严重拖慢我的项目的 build 速度
2、 echarts 合并进最终代码里会导致代码文件很大，而 webpack 并没有基于 es6 module 的自动 code split 方案（貌似 `System.import` 能解决？还没试）

不知道你有没遇上这些问题，是怎么解决的呢

**Comment by luqin** [comment]
1、按需引用模块，只依赖需要的 chart：

```
import echarts from 'echarts';
import 'echarts/chart/wordCloud';

let mychart = echarts.init(dom);
let charCloudOption = {...};
mychart.setOption(charCloudOption);
```

2、如果需要按需加载，使用 `require.ensure`

**Comment by nighca** [comment]
> 1、按需引用模块，只依赖需要的 chart：

这样也不小的。。

> 2、如果需要按需加载，使用 require.ensure

`require.ensure` 是 CommonJS 的方案，在会被 babel 转换的 es6 module 中不好使吧。

**Comment by luqin** [comment]
使用 webpack 编译就好使。

按需加载你还嫌小么？

**Comment by nighca** [comment]
:ok_hand: `require.ensure` 好使的~

**Comment by luqin** [comment]
有兴趣的话可以一起设计下 react-echarts 的api，echarts 使用 react 封装下不是很难

**Comment by nighca** [comment]
个人经验是，
1. 依赖的 `chart` 列表
2. `option`
3. `theme`

这些基本就够了，另外可能需要可以加在容器 dom 节点上的 `className`。

**Comment by nighca** [comment]
另外 echarts 现在的维护者跟我一个部门的，说想找你商量 npm 包 [echarts](https://www.npmjs.com/package/echarts) 的问题，不知道联系你没。。

**Comment by luqin** [comment]
这是要感谢我的节奏么 :joy:

**Comment by nighca** [comment]
应该是想看这个包可不可以还是交给他们自己维护，毕竟包名是唯一的

**Comment by luqin** [comment]
zrender 都没啦 :joy:

**Comment by luqin** [comment]
没事，我不累 :smile:

**Comment by hustcc** [comment]
@nighca @luqin 现在js真活跃，npm包名都是需要抢注的？和域名一样，囧了个囧~
