### ISSUE TITLE
babel&webpack打包报错

### ISSUE THREAD

**Issue by yeliex** [luqin/react-echarts#4]
- .babelrc中stage项已失效,需要用preset-stage-0来代替 http://babeljs.io/docs/plugins/preset-stage-0/
- .babelrc中options项已失效,需要用plugin-transform-runtime来代替 http://babeljs.io/docs/plugins/transform-runtime/
- .babelrc中plugin:object-transform项已失效,需要用plugin-transform-object-transform来代替 http://babeljs.io/docs/plugins/transform-object-assign/
  @luqin

**Comment by luqin** [comment]
暂时还未升级 Babel 6

**Comment by yeliex** [comment]
请问有相关计划呢 看到已经两个月未更新了 是否停止维护了

**Comment by luqin** [comment]
欢迎贡献PR    :joy:

**Comment by yeliex** [comment]
#5

**Comment by luqin** [comment]
Hi，试试 0.1.1吧，我将babel配置移除了。

另外babel升级6需要在构建工具统一处理：https://github.com/luqin/react-component-tools

**Comment by tonykaku** [comment]
弱弱的问下，能否加入鼠标点击事件的操作。。。

**Comment by luqin** [comment]
@tonykaku 能否举个栗子？支持echarts所有的功能的

**Comment by tonykaku** [comment]
@luqin 额。。。我的onClick事件返回这个
![image](https://cloud.githubusercontent.com/assets/4925947/15732440/c1e534dc-28af-11e6-881d-42ac7f3130f8.png)

**Comment by luqin** [comment]
有代码示例吗？
