### ISSUE TITLE
地图包怎么传进去？geoCreator.js:47Map china not exists. You can download map file on http://echarts.baidu.com/download-map.html

### ISSUE THREAD

**Issue by jiaoyanfei** [luqin/react-echarts#9]
地图包怎么传进去？

**Comment by luqin** [comment]
你好，需要在导入react-echarts之后自行导入地图插件

**Comment by jiaoyanfei** [comment]
在导入地图包之前需要先  echarts.registerMap(); 需要用到echarts对象，但是react-eacharts 并没有提供eacharts 对象的入口， 只提供了 option， notMerge， notRefreshImmediately 三个props 。。。这样的话，地图包即时导入进来，也无法通过echarts.registerMap(); 传进去

**Comment by luqin** [comment]
可以直接依赖下echarts，然后导入echarts进行echarts.registerMap();

**Comment by jiaoyanfei** [comment]
非常感谢您的耐心回复，问题已经解决了，原来百度echarts 3.0之后再npm 里有包， 直接 npm install echarts ，然后直接用echarts就可以了

**Comment by luqin** [comment]
是的， :+1:
